### PR TITLE
LPS-61814 Debugging output to double check suspicion that this is bei…

### PR DESCRIPTION
**Pull request by willnewbury**
…ng caused by a bundle resource not being loaded.

### CODE REVIEW

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Aborted due to known start-up issue caused by https://github.com/brianchandotcom/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged we can re-run this particular pull request.

Sorry for the inconvenience.

**Pull request closed without merging**
