### PR TITLE
LPS-54170

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @willnewbury

Can you have a look at this?
When you run SF, it will make all these vars in JavadocFormatter final and JavadocFormatter does not compile anymore.

I have had this issue before (see LPS-54901) and it has to do with the changes you made for LPS-49294.

I don't really like automatic changes by SF breaking stuff this way, because it will result in unhappy engineers complaining about it.
Can you look into this to either warn instead of autofixing or make it more strict, so we don't have these cases where compilation breaks?

Thanks!

@topolik

I added JavadocFormatter to source-formatter.properties#secure.xml.excludes.files
From looking at JavadocBuilder, it seems that this is right, but can you confirm?

**Comment by topolik** [comment]
Hi @hhuijser,

yes, that's correct, thank you.

When I run `ant format-source` in portal-impl it doesn't tell me about JavadocFormatter, do you please know where could be the problem?

**Comment by hhuijser** [comment]
Hey @topolik 

JavadocFormatter got (accidentally) ignored by SF, so it didn't show up until the commits in this pull (this one specifically: https://github.com/hhuijser/liferay-portal/commit/9de77306e68986c5d2ae0f6c921cfa37590d0887)

**Comment by topolik** [comment]
Oh, I see. Thank you!

**Comment by willnewbury** [comment]
Hey guys, sorry for the delay, I was on evp the last week and just got back. Is this still something that I should look into? As I understand it, the current case was just added to the excludes list, but the underlying behaviour (SF can cause changes that would cause compile errors) is still there.

**Comment by hhuijser** [comment]
Hey @willnewbury 

This is still something I'd like you to look into.
If you run ant format-source on this pull, you'll see the vars that change in JavadocFormatter.
Let's see if we can improve this and not have SF break stuff.

Thanks,

**Comment by hhuijser** [comment]
@willnewbury

Any update?

**Comment by willnewbury** [comment]
None so far - I have not had much of a chance to do more than look at it

**Comment by willnewbury** [comment]
For clarification - is this something where we want to change this from automatic modification to a simple warning? Outside of taking that course of action, I am not sure what there is to be done - any source-formatter change can cause errors, its just this one happens to be very brittle and complicated. There is a limit to how much more robust we can make it in the context of the current sf

**Comment by hhuijser** [comment]
I agree, that it's possible for other SF changes to cause errors, but it seems that this one happens quite a bit (I have had it happened already more than 5 times just for myself). Think this is too much, so I rather not autofix in that case.

**Pull request closed without merging**
